<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-oip-examples</artifactId>
        <version>1.5.0-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-oip-mlserver-iris-classifier</artifactId>
    <packaging>habushu</packaging>

    <name>aiSSEMBLE::Open Inference Protocol::Examples::MLServer Iris Classifier</name>
    <description>A simple iris classifier example demonstrating MLServer basics</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.48.0</version>
                <executions>
                    <execution>
                        <id>build-docker-image</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <images>
                        <image>
                            <name>boozallen/${project.artifactId}:${project.version}</name>
                            <build>
                                <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                                <contextDir>${project.basedir}</contextDir>
                                <buildx>
                                    <builderName>maven</builderName>
                                    <platforms>
                                        <platform>linux/arm64</platform>
                                    </platforms>
                                </buildx>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
