<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-parent</artifactId>
        <version>8</version>
        <relativePath />
    </parent>

    <artifactId>aissemble-open-inference-protocol</artifactId>
    <version>1.5.0-SNAPSHOT</version>

    <name>aiSSEMBLE::Open Inference Protocol</name>
    <description>Houses all of aiSSEMBLE's implementations of the Open Inference Protocol (OIP)</description>
    <packaging>pom</packaging>
    <url>https://github.com/boozallen/aissemble-open-inference-protocol</url>

    <scm>
        <connection>scm:git:https://github.com/boozallen/aissemble-open-inference-protocol.git</connection>
        <developerConnection>scm:git:https://github.com/boozallen/aissemble-open-inference-protocol.git</developerConnection>
        <url>https://github.com/boozallen/aissemble-open-inference-protocol</url>
        <tag>HEAD</tag>
    </scm>

    <organization>
        <name>Booz Allen Hamilton Inc.</name>
        <url>https://www.boozallen.com</url>
    </organization>

    <developers>
        <developer>
            <id>aissemble</id>
            <name>aiSSEMBLE Baseline Community</name>
            <organization>Booz Allen Hamilton</organization>
            <organizationUrl>https://boozallen.com</organizationUrl>
            <email>aissemble@bah.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    
    <properties>
        <version.habushu.plugin>3.3.0</version.habushu.plugin>
        <version.python>3.11.4</version.python>
    </properties>

    <modules>
        <module>aissemble-oip-core</module>
        <module>aissemble-oip-modules</module>
        <module>aissemble-oip-examples</module>
    </modules>

    <profiles>
        <profile>
            <id>default-build</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <distributionManagement>
                <snapshotRepository>
                    <id>ghcr.io</id>
                    <url>https://maven.pkg.github.com/boozallen/aissemble-open-inference-protocol</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>ci</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.technologybrewery.habushu</groupId>
                            <artifactId>habushu-maven-plugin</artifactId>
                            <version>${version.habushu.plugin}</version>
                            <configuration>                                
                                <deleteVirtualEnv>true</deleteVirtualEnv>
                                <forceSync>true</forceSync>
                                <decryptPassword>false</decryptPassword>
                                <rewriteLocalPathDepsInArchives>true</rewriteLocalPathDepsInArchives>
                                <addPypiRepoAsPackageSources>false</addPypiRepoAsPackageSources>
                                <useDevRepository>true</useDevRepository>                                
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>release</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.technologybrewery.habushu</groupId>
                            <artifactId>habushu-maven-plugin</artifactId>
                            <version>${version.habushu.plugin}</version>
                            <configuration>
                                <useDevRepository>false</useDevRepository>
                            </configuration>
                        </plugin>
                        <plugin>
                            <groupId>org.sonatype.central</groupId>
                            <artifactId>central-publishing-maven-plugin</artifactId>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.technologybrewery.habushu</groupId>
                    <artifactId>habushu-maven-plugin</artifactId>
                    <version>${version.habushu.plugin}</version>
                    <extensions>true</extensions>
                    <configuration>
                        <cacheWheels>true</cacheWheels>
                        <pythonVersion>${version.python}</pythonVersion>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <!-- Apply licenses automatically -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>