# Default values for iris-classifier
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: boozallen/aissemble-oip-mlserver-iris-classifier
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: "1.5.0-SNAPSHOT"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi