<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-inference-examples</artifactId>
        <version>1.5.0</version>
    </parent>

    <artifactId>aissemble-summarization-example</artifactId>
    <packaging>habushu</packaging>

    <name>aiSSEMBLE::Inference::Examples::Summarization</name>
    <description>
        Example demonstrating text summarization using aissemble-inference-sumy
    </description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <configuration>
                    <skipDeploy>true</skipDeploy>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>aissemble-inference-sumy</artifactId>
            <version>1.5.0</version>
            <type>habushu</type>
        </dependency>
    </dependencies>
</project>
