apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: kserve-model
spec:
  predictor:
    containers:
      - name: "aissemble-oip-kserve-containerization-docker"
        image: aissemble-oip-kserve-containerization-docker:1.0.0-SNAPSHOT
        args:
          - --enable_grpc=true
          - --grpc_port=8081
        ports:
          - name: h2c
            containerPort: 8081
            protocol: TCP