<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-oip-kserve</artifactId>
        <version>1.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-oip-kserve-inference</artifactId>
    <packaging>habushu</packaging>

    <name>aiSSEMBLE::Open Inference Protocol Examples::KServe Inference</name>
    <description>Example of how to use the KServe Open Interface protocol</description>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>aissemble-open-inference-protocol-kserve</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>aissemble-open-inference-protocol-shared</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
    </dependencies>

</project>
