<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-oip-kserve-containerization</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-oip-kserve-containerization-docker</artifactId>
    <packaging>docker-build</packaging>

    <name>aiSSEMBLE::Open Inference Protocol Examples::KServe Containerization Docker</name>
    <description>Example of how to use the containerize dependencies goal on a aiSSEMBLE OIP for KServe project</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>dockerize</id>
                        <goals>
                            <goal>containerize-dependencies</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <dockerfile>./Dockerfile</dockerfile>
                            <dockerBuilderBase>docker.io/python:3.12</dockerBuilderBase>
                            <dockerFinalBase>docker.io/python:3.12-slim</dockerFinalBase>
                            <updateDockerfile>true</updateDockerfile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.technologybrewery.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>build-docker-image</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- Example expected to be run locally so skipping push -->
                    <skipPush>true</skipPush>
                    <images>
                        <image>
                            <name>${project.artifactId}:${project.version}</name>
                            <build>
                                <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                                <buildx>
                                    <builderName>default</builderName>
                                    <!-- use a separate state dir to ensure pre-configured credentials are not deleted -->
                                    <dockerStateDir>~/.docker/fabric8</dockerStateDir>
                                    <platforms>
                                        <platform>linux/amd64</platform>
                                    </platforms>
                                </buildx>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>aissemble-oip-kserve-inference</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
    </dependencies>

</project>
