<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-inference-modules</artifactId>
        <version>1.5.1-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-inference-yolo</artifactId>
    <packaging>habushu</packaging>

    <name>aiSSEMBLE::Inference::Modules::YOLO</name>
    <description>YOLO model family support for aiSSEMBLE Inference</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Helps the build reactor order the build appropriately: -->
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>aissemble-inference-common-test</artifactId>
            <version>1.5.1-SNAPSHOT</version>
            <type>habushu</type>
            <scope>test</scope>
        </dependency>
    </dependencies>


</project>
