<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-oip-modules</artifactId>
        <version>1.5.0-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-oip-sumy</artifactId>
    <packaging>habushu</packaging>

    <name>aiSSEMBLE::Open Inference Protocol::Modules::sumy</name>
    <description>sumy model family support for aiSSEMBLE OIP</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Helps the build reactor order the build appropriately: -->
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>aissemble-oip-common-test</artifactId>
            <version>1.5.0-SNAPSHOT</version>
            <type>habushu</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
