# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build aissemble-open-inference-protocol

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'
        type: string
  schedule:
  - cron: "0 6 * * *" # every day at 6am UTC

jobs:
  build:
    if: github.event.review.state == 'approved' || github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          sonatype-central-user: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_USER }}
          sonatype-central-key: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_KEY }}
          github-actor: \${env.GITHUB_ACTOR}
          github-token: \${env.GITHUB_TOKEN}
          package-index: dev-pypi
          pypi-username: ${{ secrets.TEST_PYPI_USERNAME }}
          pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}

      # Run build and deploy test artifacts
      - name: Build aissemble-open-inference-protocol
        run: mvn clean deploy -B -U -Pbuild,ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
