# This workflow kicks off the release job of aiSSEMBLE Inference
# and deploys artifacts to Maven Central, ghcr.io and pypi

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release aissemble-inference

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: "Release Branch (default: release-{releaseVersion})"
        required: false
        type: string
      releaseVersion:
        description: "Release Version (X.Y.Z)"
        required: true
        type: string
      developmentVersion:
        description: "Next Dev Version"
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Point to default release branch i.e. release-{releaseVersion} if none specified
        id: branch
        run: |
          echo "release-branch=$( [ "${{ inputs.releaseBranch }}" != "" ] && echo "${{ inputs.releaseBranch }}" || echo "release-${{ inputs.releaseVersion }}")" >> $GITHUB_OUTPUT
      - name: Print release parameters
        run: |
          echo "Releasing with the following parameters"
          echo "Release Branch:  ${{ steps.branch.outputs.release-branch }}"
          echo "Release version: ${{ inputs.releaseVersion }}"
          echo "Next Development version:  ${{ inputs.developmentVersion }}"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.release-branch }}
      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          sonatype-central-user: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_USER }}
          sonatype-central-key: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_KEY }}
          package-index: pypi
          pypi-username: ${{ secrets.PYPI_USERNAME }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
      - name: Release aissemble-inference
        run: |
          git config --local user.email "aissemble@bah.com"
          git config --local user.name "Github Actions"
          mvn -B release:clean release:prepare release:perform -Pci,release -DreleaseVersion=${{ inputs.releaseVersion }} -DdevelopmentVersion=${{ inputs.developmentVersion }} -Dmaven.build.cache.enabled=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}